### ISSUE TITLE
WebDriver line 201, 209, 672

### ISSUE THREAD

**Issue by ChotaVeer** [maximedrn/opensea_automatic_uploader#23]
I'm not a coder, So can you please make it easy for me how to solve it?
Traceback (most recent call last):
  File "C:\Users\usman\Downloads\Compressed\opensea_automatic_uploader-master\opensea_automatic_uploader-master\main.py", line 672, in <module>
    web = Webdriver()  # Start a new webdriver and init its methods.
  File "C:\Users\usman\Downloads\Compressed\opensea_automatic_uploader-master\opensea_automatic_uploader-master\main.py", line 201, in __init__
    self.driver = self.webdriver()  # Start new webdriver.
  File "C:\Users\usman\Downloads\Compressed\opensea_automatic_uploader-master\opensea_automatic_uploader-master\main.py", line 209, in webdriver
    driver = webdriver.Chrome(service=Service(  # DeprecationWarning using
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service'

**Comment by maximedrn** [comment]
Can you tell me what version of Google Chrome you have?

**Comment by ChotaVeer** [comment]
Version 96.0.4664.110 (Official Build) (64-bit)

**Comment by maximedrn** [comment]
It's a new feature from the Selenium module to prevent deprecation. It seems that this error do not have real solution:
> Sadly, that very change seems to cause inconsistency and mystery.

Try to reinstall the module by typing these lines in your command prompt:
```
pip uninstall selenium
```
then:
```
pip install selenium
```
If it still doesn't work, can you tell me what version of Python do you have?
Type ``python`` in your command prompt.

**Comment by ChotaVeer** [comment]
Python 3.10.1

**Comment by ChotaVeer** [comment]
Traceback (most recent call last):
  File "C:\Users\usman\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\usman\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\usman\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\usman\Downloads\Compressed\opensea_automatic_uploader-master\opensea_automatic_uploader-master\main.py", line 672, in <module>
    web = Webdriver()  # Start a new webdriver and init its methods.
  File "C:\Users\usman\Downloads\Compressed\opensea_automatic_uploader-master\opensea_automatic_uploader-master\main.py", line 201, in __init__
    self.driver = self.webdriver()  # Start new webdriver.
  File "C:\Users\usman\Downloads\Compressed\opensea_automatic_uploader-master\opensea_automatic_uploader-master\main.py", line 209, in webdriver
    driver = webdriver.Chrome(service=Service(  # DeprecationWarning using
  File "C:\Users\usman\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\usman\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Users\usman\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

**Comment by ChotaVeer** [comment]
1: open CMD
2: cd (directory)
3- python main.py
then it's starting this
Choose an action to perform:
Is it right way to work with?

**Comment by maximedrn** [comment]
Yes. Do you have you the `chromedriver.exe` under the path `C:\Users\usman\Downloads\Compressed\opensea_automatic_uploader-master\opensea_automatic_uploader-master\assets\`?
You have this error while launching the Webdriver class:
``selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home``

**Comment by maximedrn** [comment]
The bot needs an executable (chromedriver.exe) that need to be located in the `assets/` folder of the repository.

**Comment by ChotaVeer** [comment]
okay, so everything is done. Just have this error
https://ctrlv.link/ifmw

**Comment by ChotaVeer** [comment]
Stats name is not placing using xls

**Comment by maximedrn** [comment]
Can you send me the stats details you want to upload on Opensea

**Comment by maximedrn** [comment]
Have you write your levels name between " " ?
